[phases.setup]
nixPkgs = ["python311"]

[phases.install]
cmds = [
  "pip install -r chainlit-app/requirements.txt"
]

[start]
cmd = "cd chainlit-app && chainlit run app.py --host 0.0.0.0 --port $PORT"
